### ISSUE TITLE
Unexplained AI income in 1.4.1.-classicqueue

### ISSUE THREAD

**Issue by nmoskopp** [MlemandPurrs/raplusmod#12]
In a replay I noticed the AI getting 20% more income than the resources it harvested.

The AI also got some other income from a source I could not identify. At the end of the replay it had more income than there were resources on the map, without having any buildings that generate passive income.

**Comment by MlemandPurrs** [comment]
At that version the AI was set to build faster & cheaper, and also earn more resources than the player. 
In later version(s) exposed this to the player in the form of a lobby tickbox option as have decided its rather unfair to be forced on.

**Comment by nmoskopp** [comment]
Ok cool.
