### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by olliewuk** [MlemandPurrs/raplusmod#4]
Hi,

Have a crash with this mod, opened an issue on OpenRA:
https://github.com/OpenRA/OpenRA/issues/18603

They said it due to an issue with:
https://docs.openra.net/en/latest/release/traits/#mpstartlocations

**Comment by MlemandPurrs** [comment]
ah i see. thanks for report.
you have been using the Heavy Support option at lobby, right ?
one of the two Soviet starting unit sets has not their unit ids updated, was supposed to be 3tnk.1b remaint as 2tnk.soviet instead.
Fix coming soon.

**Comment by olliewuk** [comment]
Correct.. Heavy Support

**Comment by MlemandPurrs** [comment]
made a new release that is supposed to get it fixed:
https://github.com/MlemandPurrs/raplusmod/releases/tag/v.1.3.8-crashfixes
tell me again if its still occuring.
